project:
  type: website
  output-dir: ../docs

website:
  title: "Bachelor Thesis"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "aoa.R"
        file: implementation_AOA.qmd
      - text: "trainDI.R"
        file: implementation_TRAINDI.qmd
    tools:
      - icon: github
        href: https://github.com/fab-scm/CAST

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



